Repository uzh-bf/klicker-api, pull requests merged in 2018-07, with the labels that each got.

#365 Update graphql
  package.json
  yarn.lock
Labels: dependencies

#366 Server Side Validation
  package.json
  src/constants.js
  src/integration/integration.test.js
  src/models/Session.js
  src/models/User.js
  src/services/auth.js
  src/services/auth.test.js
  src/services/questions.test.js
  src/services/sessionExec.test.js
  src/services/sessionMgr.test.js
  yarn.lock
Labels: enhancement

#367 Update dependency mongoose to v5.2.0
  package.json
  yarn.lock
Labels: dependencies

#369 Update dependency elastic-apm-node to v1.8.2
  package.json
  yarn.lock
Labels: dependencies

#368 Update dependency mongoose to v5.2.1
  package.json
  yarn.lock
Labels: dependencies

#372 Update database
  package.json
  yarn.lock
Labels: dependencies

#373 Update node:8-alpine Docker digest to d3ecde
  Dockerfile
Labels: dependencies

#374 Update dependency graphql-tools to v3.0.5
  package.json
  yarn.lock
Labels: dependencies

#375 Update dependency eslint to v5.1.0
  package.json
  yarn.lock
Labels: dependencies

#376 Update dependency apollo-server-express to v2.0.0-rc.7
  package.json
  yarn.lock
Labels: dependencies

#378 Update dependency nodemon to v1.18.0
  package.json
  yarn.lock
Labels: dependencies

#377 Update dependency jest to v23.4.0
  package.json
  yarn.lock
Labels: dependencies

#379 Publishing Evaluations
  src/integration/__snapshots__/integration.test.js.snap
  src/integration/integration.test.js
  src/integration/queries.js
  src/lib/loaders.js
  src/models/Session.js
  src/resolvers/questionInstances.js
  src/resolvers/sessions.js
  src/schema.js
  src/types/Question.js
  src/types/QuestionInstance.js
  src/types/Session.js
  src/types/questionTypes/FREEQuestionOptions.js
  src/types/questionTypes/FREEQuestionResults.js
  src/types/questionTypes/SCQuestionOptions.js
  src/types/questionTypes/SCQuestionResults.js
Labels: feature

#383 Update dependency babel-eslint to v8.2.6
  package.json
  yarn.lock
Labels: dependencies

#384 Editing Sessions
  package.json
  src/constants.js
  src/integration/__snapshots__/integration.test.js.snap
  src/integration/integration.test.js
  src/integration/mutations.js
  src/integration/mutations/ActivateNextBlockMutation.graphql
  src/integration/mutations/ActivateNextBlockSerializer.js
  src/integration/mutations/AddConfusionTSMutation.graphql
  src/integration/mutations/AddFeedbackMutation.graphql
  src/integration/mutations/AddResponseMutation.graphql
  src/integration/mutations/ArchiveQuestionsMutation.graphql
  src/integration/mutations/ArchiveQuestionsSerializer.js
  src/integration/mutations/ChangePasswordMutation.graphql
  src/integration/mutations/ChangePasswordSerializer.js
  src/integration/mutations/CreateQuestionMutation.graphql
  src/integration/mutations/CreateQuestionSerializer.js
  src/integration/mutations/CreateSessionMutation.graphql
  src/integration/mutations/CreateSessionSerializer.js
  src/integration/mutations/DeleteFeedbackMutation.graphql
  src/integration/mutations/EndSessionMutation.graphql
  src/integration/mutations/LoginMutation.graphql
  src/integration/mutations/LogoutMutation.graphql
  src/integration/mutations/ModifyQuestionMutation.graphql
  src/integration/mutations/ModifySessionMutation.graphql
  src/integration/mutations/PauseSessionMutation.graphql
  src/integration/mutations/RegistrationMutation.graphql
  src/integration/mutations/RegistrationSerializer.js
  src/integration/mutations/RequestPasswordMutation.graphql
  src/integration/mutations/StartAndEndSessionSerializer.js
  src/integration/mutations/StartSessionMutation.graphql
  src/integration/mutations/UpdateSessionSettingsMutation.graphql
  src/integration/mutations/UpdateSessionSettingsSerializer.js
  src/integration/mutations/index.js
  src/integration/queries.js
  src/integration/queries/AccountSummaryQuery.graphql
  src/integration/queries/JoinSessionQuery.graphql
  src/integration/queries/JoinSessionSerializer.js
  src/integration/queries/QuestionDetailsQuery.graphql
  src/integration/queries/QuestionDetailsSerializer.js
  src/integration/queries/QuestionListQuery.graphql
  src/integration/queries/RunningSessionQuery.graphql
  src/integration/queries/RunningSessionSerializer.js
  src/integration/queries/SessionEvaluationQuery.graphql
  src/integration/queries/SessionEvaluationSerializer.js
  src/integration/queries/SessionListQuery.graphql
  src/integration/queries/SessionPublicEvaluationQuery.graphql
  src/integration/queries/SessionPublicEvaluationSerializer.js
  src/integration/queries/TagListQuery.graphql
  src/integration/queries/index.js
  src/lib/utils.js
  src/resolvers/sessions.js
  src/schema.js
  src/services/__snapshots__/sessionMgr.test.js.snap
  src/services/sessionMgr.js
  src/services/sessionMgr.test.js
  src/types/Session.js
  yarn.lock
Labels: feature

#385 Update dependency jest to v23.4.1
  package.json
  yarn.lock
Labels: dependencies

#386 Update dependency nodemon to v1.18.2
  package.json
  yarn.lock
Labels: dependencies

#388 Update dependency apollo-server-express to v2.0.0-rc.8
  package.json
  yarn.lock
Labels: dependencies

#392 Update dependency nodemon to v1.18.3
  package.json
  yarn.lock
Labels: dependencies

#391 Update dependency apollo-server-express to v2.1.0-alpha.2
  package.json
  yarn.lock
Labels: dependencies

#371 File Uploads to S3, Images for Questions
  .env.prod
  docker-compose.yml
  package.json
  src/lib/loaders.js
  src/models/File.js
  src/models/QuestionVersion.js
  src/models/User.js
  src/models/index.js
  src/resolvers/files.js
  src/schema.js
  src/services/__snapshots__/questions.test.js.snap
  src/services/files.js
  src/services/questions.js
  src/services/sessionExec.js
  src/types/File.js
  src/types/Question.js
  src/types/User.js
  src/types/index.js
  yarn.lock
Labels: feature

#394 Pin Docker digests
  docker-compose.yml
Labels: dependencies

#401 Update dependency mongoose to v5.2.5
  package.json
  yarn.lock
Labels: dependencies

#400 Update dependency helmet to v3.13.0
  package.json
  yarn.lock
Labels: dependencies

#399 Update minio/minio:latest Docker digest to ed0c46
  docker-compose.yml
Labels: dependencies

#398 Update dependency eslint to v5.2.0
  package.json
  yarn.lock
Labels: dependencies

#397 Update dependency aws-sdk to v2.279.1
  package.json
  yarn.lock
Labels: dependencies

#396 Update dependency subscriptions-transport-ws to v0.9.13
  package.json
  yarn.lock
Labels: dependencies

#403 Update dependency v8n to v1.1.0
  package.json
  yarn.lock
Labels: dependencies

#402 Update dependency aws-sdk to v2.280.1
  package.json
  yarn.lock
Labels: dependencies

#407 Update dependency v8n to v1.1.2
  package.json
  yarn.lock
Labels: dependencies

#410 Update dependency subscriptions-transport-ws to v0.9.14
  package.json
  yarn.lock
Labels: dependencies

#409 Update dependency aws-sdk to v2.282.1
  package.json
  yarn.lock
Labels: dependencies

#408 General Improvements
  package.json
  renovate.json
  src/integration/__snapshots__/integration.test.js.snap
  src/integration/integration.test.js
  src/integration/queries/JoinSessionQuery.graphql
  src/integration/queries/JoinSessionSerializer.js
  src/resolvers/users.js
  src/schema.js
  src/services/sessionExec.js
  src/types/Question.js
  src/types/Session.js
  src/types/User.js
  yarn.lock
Labels: bug, enhancement

#411 Update dependency jest to v23.4.2
  package.json
  yarn.lock
Labels: dependencies

#413 Update dependency elastic-apm-node to v1.10.0
  package.json
  yarn.lock
Labels: dependencies

#414 Update dependency aws-sdk to v2.283.1
  package.json
  yarn.lock
Labels: dependencies

#412 User Settings
  .eslintrc
  .prettierignore
  .prettierrc.js
  package.json
  src/app.js
  src/constants.js
  src/integration/integration.test.js
  src/integration/mutations/ActivateNextBlockSerializer.js
  src/integration/mutations/ArchiveQuestionsSerializer.js
  src/integration/mutations/CreateQuestionSerializer.js
  src/integration/mutations/CreateSessionSerializer.js
  src/integration/mutations/LoginMutation.graphql
  src/integration/mutations/ModifyUserMutation.graphql
  src/integration/mutations/RegistrationSerializer.js
  src/integration/mutations/StartAndEndSessionSerializer.js
  src/integration/mutations/index.js
  src/integration/queries/AccountSummaryQuery.graphql
  src/integration/queries/CheckAvailabilityQuery.graphql
  src/integration/queries/JoinSessionSerializer.js
  src/integration/queries/QuestionDetailsSerializer.js
  src/integration/queries/RunningSessionSerializer.js
  src/integration/queries/SessionEvaluationSerializer.js
  src/integration/queries/SessionPublicEvaluationSerializer.js
  src/integration/queries/index.js
  src/lib/draft.js
  src/lib/loaders.js
  src/lib/test/serializers.js
  src/lib/test/setup.js
  src/lib/utils.js
  src/lib/validators.js
  src/models/User.js
  src/resolvers/files.js
  src/resolvers/questionInstances.js
  src/resolvers/questions.js
  src/resolvers/sessions.js
  src/resolvers/subscriptions.js
  src/resolvers/users.js
  src/schema.js
  src/scripts/normalizeEmails.js
  src/server.js
  src/services/accounts.js
  src/services/accounts.test.js
  src/services/auth.js
  src/services/auth.test.js
  src/services/files.js
  src/services/questions.js
  src/services/questions.test.js
  src/services/sessionExec.js
  src/services/sessionExec.test.js
  src/services/sessionMgr.js
  src/services/sessionMgr.test.js
  src/types/Question.js
  src/types/User.js
  yarn.lock
Labels: feature
