Repository uzh-bf/klicker-api, pull requests merged in 2018-03, with the labels that each got.

#234 Update dependency dotenv to v5.0.1
  package.json
  yarn.lock
Labels: dependencies

#238 Update Dockerfile node image 8-alpine digest (6bb963)
  Dockerfile
Labels: dependencies

#236 Update dependency nodemon to v1.17.1
  package.json
  yarn.lock
Labels: dependencies

#235 Update dependency elastic-apm-node to v1.1.0
  package.json
  yarn.lock
Labels: dependencies

#237 Update dependency prettier to v1.11.1
  package.json
  yarn.lock
Labels: dependencies

#240 Update student mutations for string returns
  src/integration/__snapshots__/integration.test.js.snap
  src/integration/mutations.js
  src/resolvers/questionInstances.js
  src/resolvers/sessions.js
  src/schema.js
Labels: enhancement

#241 Pin Dependencies
  package.json
  yarn.lock
Labels: dependencies

#242 Update Dockerfile node image 8-alpine digest (06ebd9)
  Dockerfile
Labels: dependencies

#243 Update database packages
  package.json
  yarn.lock
Labels: dependencies

#244 Update dependency cross-env to v5.1.4
  package.json
  yarn.lock
Labels: dependencies

#245 Update dependency elastic-apm-node to v1.1.1
  package.json
  yarn.lock
Labels: dependencies

#246 Update dependency express-jwt to v5.3.1
  package.json
  yarn.lock
Labels: dependencies

#247 Update dependency nodemailer to v4.6.2
  package.json
  yarn.lock
Labels: dependencies

#248 Update dependency express to v4.16.3
  package.json
  yarn.lock
Labels: dependencies

#249 Update dependency mongoose to v5.0.10
  package.json
  yarn.lock
Labels: dependencies

#250 Update dependency nodemailer to v4.6.3
  package.json
  yarn.lock
Labels: dependencies

#251 Update dependency nodemon to v1.17.2
  package.json
  yarn.lock
Labels: dependencies

#255 Update dependency graphql-tools to v2.22.0
  package.json
  yarn.lock
Labels: dependencies

#252 Update dependency apollo-engine to v0.9.1
  package.json
  yarn.lock
Labels: dependencies

#253 Update dependency elastic-apm-node to v1.2.0
  package.json
  yarn.lock
Labels: dependencies

#254 Update dependency eslint to v4.18.2
  package.json
  yarn.lock
Labels: dependencies

#256 Archiving questions
  package.json
  src/integration/__snapshots__/integration.test.js.snap
  src/integration/integration.test.js
  src/integration/mutations.js
  src/integration/queries.js
  src/lib/test/serializers.js
  src/models/Question.js
  src/resolvers/questions.js
  src/schema.js
  src/services/__snapshots__/questions.test.js.snap
  src/services/__snapshots__/sessionMgr.test.js.snap
  src/services/questions.js
  src/services/questions.test.js
  src/services/sessionMgr.js
  src/services/sessionMgr.test.js
  src/types/Question.js
Labels: feature

#257 Update Dockerfile node image 8-alpine digest (a55d3e)
  Dockerfile
Labels: dependencies

#258 Update dependency elastic-apm-node to v1.2.1
  package.json
  yarn.lock
Labels: dependencies

#260 Update dependency helmet to v3.12.0
  package.json
  yarn.lock
Labels: dependencies

#261 Update dependency jsonwebtoken to v8.2.0
  package.json
  yarn.lock
Labels: dependencies

#262 Update dependency moment to v2.21.0
  package.json
  yarn.lock
Labels: dependencies

#263 Update dependency request to v2.85.0
  package.json
  yarn.lock
Labels: dependencies

#264 Update graphql packages
  package.json
  yarn.lock
Labels: dependencies

#265 Update dependency apollo-engine to v1
  package.json
  yarn.lock
Labels: dependencies

#267 Docker Best Practices
  .env.prod
  Dockerfile
  docker-compose.yml
  process.json
Labels: enhancement

#268 Rework of the Login process
  src/integration/__snapshots__/integration.test.js.snap
  src/integration/integration.test.js
  src/integration/mutations.js
  src/lib/test/setup.js
  src/schema.js
  src/services/auth.js
  src/services/auth.test.js
  src/services/questions.test.js
  src/services/sessionExec.test.js
  src/services/sessionMgr.test.js
Labels: enhancement

#269 INVALID_LOGIN redirect
  src/services/auth.js
Labels: enhancement

#272 Update dependency elastic-apm-node to v1.3.0
  package.json
  yarn.lock
Labels: dependencies

#266 Update database packages
  package.json
  yarn.lock
Labels: dependencies

#270 Update dependency apollo-engine to v1.0.4
  package.json
  yarn.lock
Labels: dependencies

#273 Update dependency eslint to v4.19.1
  package.json
  yarn.lock
Labels: dependencies

#274 Update dependency jest to v22.4.3
  package.json
  yarn.lock
Labels: dependencies

#271 Update graphql packages
  package.json
  yarn.lock
Labels: dependencies

#275 Update dependency mongoose to v5.0.12
  package.json
  yarn.lock
Labels: dependencies

#276 Logout
  src/integration/__snapshots__/integration.test.js.snap
  src/integration/integration.test.js
  src/integration/mutations.js
  src/resolvers/users.js
  src/schema.js
  src/services/auth.js
  src/services/auth.test.js
Labels: feature
