Repository uzh-bf/klicker-api, pull requests merged in 2018-08, with the labels that each got.

#418 Update dependency aws-sdk to v2.284.1
  package.json
  yarn.lock
Labels: dependencies

#417 Update dependency v8n to v1.2.0
  package.json
  yarn.lock
Labels: dependencies

#416 Update dependency elastic-apm-node to v1.10.1
  package.json
  yarn.lock
Labels: dependencies

#419 Update react monorepo to v16.4.2
  package.json
  yarn.lock
Labels: dependencies

#420 Update dependency graphql-tools to v3.1.0
  package.json
  yarn.lock
Labels: dependencies

#422 Add Health Check for MongoDB and Redis connections
  Dockerfile
  src/app.js
Labels: enhancement

#421 Update dependency aws-sdk to v2.285.1
  package.json
  yarn.lock
Labels: dependencies

#424 Update dependency aws-sdk to v2.286.2
  package.json
  yarn.lock
Labels: dependencies

#423 Update dependency graphql-tools to v3.1.1
  package.json
  yarn.lock
Labels: dependencies

#426 Configuration Management
  .env.prod
  package.json
  src/app.js
  src/klicker.conf.js
  src/lib/test/setup.js
  src/redis.js
  src/resolvers/users.js
  src/server.js
  src/services/auth.js
  src/services/files.js
  src/services/notifications.js
  src/services/sessionExec.js
  yarn.lock
Labels: enhancement

#428 Update dependency express-rate-limit to v2.12.1
  package.json
  yarn.lock
Labels: dependencies

#427 Check existence of email and shortname on signup
  src/services/auth.js
Labels: enhancement

#429 Update dependency eslint to v5.3.0
  package.json
  yarn.lock
Labels: dependencies

#431 Update dependency aws-sdk to v2.287.0
  package.json
  yarn.lock
Labels: dependencies

#435 Update dependency prettier to v1.14.2
  package.json
  yarn.lock
Labels: dependencies

#434 Update dependency elastic-apm-node to v1.10.2
  package.json
  yarn.lock
Labels: dependencies

#433 Update dependency aws-sdk to v2.289.0
  package.json
  yarn.lock
Labels: dependencies

#432 Update dependency express-rate-limit to v2.12.2
  package.json
  yarn.lock
Labels: dependencies

#436 Improve server-side validation of FREE_RANGE questions
  src/services/sessionExec.js
  src/services/sessionExec.test.js
Labels: enhancement

#437 Deleting Responses
  src/integration/__snapshots__/integration.test.js.snap
  src/integration/integration.test.js
  src/integration/mutations/DeleteResponseMutation.graphql
  src/integration/mutations/index.js
  src/resolvers/questionInstances.js
  src/schema.js
  src/services/sessionExec.js
Labels: feature

#438 Update dependency aws-sdk to v2.290.0
  package.json
  yarn.lock
Labels: dependencies

#451 Update dependency v8n to v1.2.1
  package.json
  yarn.lock
Labels: dependencies

#449 Update dependency elastic-apm-node to v1.11.0
  package.json
  yarn.lock
Labels: dependencies

#448 Update dependency nodemailer to v4.6.8
  package.json
  yarn.lock
Labels: dependencies

#447 Update dependency apollo-server-express to v2.0.3
  package.json
  yarn.lock
Labels: dependencies

#445 Update redis:3 Docker digest to 93edc9
  docker-compose.yml
Labels: dependencies

#444 Update node:8 Docker digest to cf4ea9
  Dockerfile
Labels: dependencies

#443 Update eslint
  package.json
  yarn.lock
Labels: dependencies

#441 Update dependency aws-sdk to v2.296.0
  package.json
  yarn.lock
Labels: dependencies

#440 Update dependency request to v2.88.0
  package.json
  yarn.lock
Labels: dependencies

#450 Update dependency validator to v10.6.0
  package.json
  yarn.lock
Labels: dependencies
