Repository uzh-bf/klicker-api, pull requests merged in 2018-09, with the labels that each got.

#460 Update dependency elastic-apm-node to v1.12.0
  package.json
  yarn.lock
Labels: dependencies

#459 Update dependency nodemon to v1.18.4
  package.json
  yarn.lock
Labels: dependencies

#458 Update dependency v8n to v1.2.2
  package.json
  yarn.lock
Labels: dependencies

#457 Update eslint
  package.json
  yarn.lock
Labels: dependencies

#454 Update dependency express-rate-limit to v2.14.2
  package.json
  yarn.lock
Labels: dependencies

#452 Update dependency aws-sdk to v2.307.0
  package.json
  yarn.lock
Labels: dependencies

#463 Update dependency graphql to v14
  package.json
  src/integration/integration.test.js
  yarn.lock
Labels: dependencies

#462 Update database (patch)
  .env.travis
  package.json
  src/lib/test/setup.js
  src/models/User.js
  yarn.lock
Labels: dependencies

#456 Update dependency validator to v10.7.1
  package.json
Labels: dependencies

#446 Update dependency ioredis to v4
  package.json
  yarn.lock
Labels: dependencies

#464 Upgrade to NodeJS 10
  Dockerfile
  Dockerfile.dev
  package.json
  src/app.js
  src/resolvers/questionInstances.js
  src/resolvers/sessions.js
  src/schema.js
  src/scripts/normalizeEmails.js
  src/services/accounts.test.js
  src/services/questions.test.js
  src/services/sessionExec.test.js
  src/services/sessionMgr.test.js
  src/types/File.js
  src/types/Question.js
  src/types/QuestionInstance.js
  src/types/Session.js
  src/types/Tag.js
  src/types/User.js
  yarn.lock
Labels: enhancement

#475 Update dependency lodash to v4.17.11
  package.json
  yarn.lock
Labels: dependencies

#474 Update dependency morgan to v1.9.1
  package.json
  yarn.lock
Labels: dependencies

#470 Update redis:3 Docker digest to 52d18d
  docker-compose.prod.yml
  docker-compose.yml
Labels: dependencies

#469 Update dependency aws-sdk to v2.314.0
  package.json
  yarn.lock
Labels: dependencies

#468 Update dependency handlebars to v4.0.12
  package.json
  yarn.lock
Labels: dependencies

#467 Update dependency raven to v2.6.4
  package.json
  yarn.lock
Labels: dependencies

#471 Update dependency supertest to v3.3.0
  package.json
Labels: dependencies

#473 Update dependency jest to v23.6.0
  package.json
  yarn.lock
Labels: dependencies

#465 Update graphql (patch)
  package.json
  yarn.lock
Labels: dependencies

#466 Update dependency mongoose to v5.2.14
  package.json
  yarn.lock
Labels: dependencies

#472 Update react monorepo to v16.5.0
  package.json
  yarn.lock
Labels: dependencies

#482 Update dependency graphql-iso-date to v3.6.1
  package.json
  yarn.lock
Labels: dependencies

#481 Update dependency eslint to v5.6.0
  package.json
  yarn.lock
Labels: dependencies

#479 Update dependency apollo-server-express to v2.0.7
  package.json
  yarn.lock
Labels: dependencies

#480 Update database (patch)
  package.json
  yarn.lock
Labels: dependencies

#477 Update react monorepo to v16.5.1 (patch)
  package.json
  yarn.lock
Labels: dependencies

#478 Update dependency aws-sdk to v2.315.0
  package.json
  yarn.lock
Labels: dependencies

#483 Update dependency graphql-subscriptions to v1
  package.json
  yarn.lock
Labels: dependencies

#486 Update react monorepo to v16.5.2 (patch)
  package.json
  yarn.lock
Labels: dependencies

#485 Update dependency subscriptions-transport-ws to v0.9.15
  package.json
  yarn.lock
Labels: dependencies

#487 Update dependency aws-sdk to v2.317.0
  package.json
  yarn.lock
Labels: dependencies

#489 Performance improvements for running sessions
  .env.travis
  .travis.yml
  docker-compose.yml
  package.json
  src/integration/__snapshots__/integration.test.js.snap
  src/lib/test/setup.js
  src/redis.js
  src/resolvers/questionInstances.js
  src/services/__snapshots__/sessionExec.test.js.snap
  src/services/__snapshots__/sessionMgr.test.js.snap
  src/services/sessionExec.js
  src/services/sessionExec.test.js
  src/services/sessionMgr.js
  src/services/sessionMgr.test.js
  yarn.lock
Labels: feature

#496 Update dependency convict to v4.4.0
  package.json
  yarn.lock
Labels: dependencies

#455 Update dependency express-rate-limit to v3
  CHANGELOG.md
  package.json
  src/app.js
  src/klicker.conf.js
  yarn.lock
Labels: dependencies, waiting

#497 Update dependency aws-sdk to v2.321.0
  package.json
  yarn.lock
Labels: dependencies
