Repository uzh-bf/klicker-api, pull requests merged in 2018-02, with the labels that each got.

#199 Update dependency elastic-apm-node to v1.0.1
  package.json
  yarn.lock
Labels: dependencies

#201 Update dependency mongoose to v5.0.4
  package.json
  yarn.lock
Labels: dependencies

#200 Update dependency helmet to v3.11.0
  package.json
  yarn.lock
Labels: dependencies

#202 Update dependency jest to v22.2.2
  package.json
  yarn.lock
Labels: dependencies

#203 General improvements
  .env
  src/app.js
  src/resolvers/questions.js
  src/resolvers/sessions.js
  src/resolvers/tags.js
Labels: enhancement, feature

#171 Renovate graphql packages
  package.json
  src/lib/test/setup.js
  yarn.lock
Labels: dependencies

#204 Update dependency apollo-engine to v0.8.10
  package.json
  yarn.lock
Labels: dependencies

#205 Update dependency elastic-apm-node to v1.0.3
  package.json
  yarn.lock
Labels: dependencies

#206 Update dependency mongoose to v5.0.5
  package.json
  yarn.lock
Labels: dependencies

#208 Update dependency prettier-eslint-cli to v4.7.1
  package.json
  yarn.lock
Labels: dependencies

#209 Update Dockerfile node image 8-alpine digest (b0f4ff)
  Dockerfile
Labels: dependencies

#207 Update dependency jest to v22.3.0
  package.json
  yarn.lock
Labels: dependencies

#210 General improvements
  src/app.js
  src/integration/__snapshots__/integration.test.js.snap
  src/integration/integration.test.js
  src/integration/queries.js
  src/lib/test/serializers.js
  src/lib/test/setup.js
  src/models/QuestionInstance.js
  src/models/Session.js
  src/queryMap.json
  src/resolvers/sessions.js
  src/schema.js
  src/services/__snapshots__/questions.test.js.snap
  src/services/__snapshots__/sessionExec.test.js.snap
  src/services/__snapshots__/sessionMgr.test.js.snap
  src/services/questions.js
  src/services/questions.test.js
  src/services/sessionExec.js
  src/services/sessionMgr.js
  src/services/sessionMgr.test.js
  src/types/QuestionInstance.js
  src/types/Session.js
Labels: enhancement, feature

#211 Password Reset
  .env
  package.json
  secret.yaml
  src/app.js
  src/integration/integration.test.js
  src/integration/mutations.js
  src/queryMap.json
  src/resolvers/users.js
  src/schema.js
  src/services/auth.js
  src/services/auth.test.js
  src/services/emails.js
  src/services/emails/passwordReset.hbs
  yarn.lock
Labels: feature

#212 Confusion Barometer
  src/integration/__snapshots__/integration.test.js.snap
  src/integration/integration.test.js
  src/models/ConfusionTimestep.js
  src/services/__snapshots__/sessionExec.test.js.snap
  src/services/sessionExec.test.js
Labels: enhancement

#213 Pin Dependencies
  package.json
  yarn.lock
Labels: dependencies

#214 Update dependency compression to v1.7.2
  package.json
  yarn.lock
Labels: dependencies

#215 Update dependency graphql to v0.13.1
  package.json
  yarn.lock
Labels: dependencies

#216 Update dependency mongoose to v5.0.6
  package.json
  yarn.lock
Labels: dependencies

#218 Update dependency lint-staged to v6.1.1
  package.json
  yarn.lock
Labels: dependencies

#219 Update dependency nodemon to v1.15.0
  package.json
  yarn.lock
Labels: dependencies

#220 Update pm2
  Dockerfile
Labels: bug

#217 Renovate eslint packages
  package.json
  src/app.js
  yarn.lock
Labels: dependencies

#221 General improvements
  src/services/auth.test.js
  src/services/sessionExec.js
Labels: feature

#222 Update dependency nodemailer to v4.5.0
  package.json
  yarn.lock
Labels: dependencies

#224 Update dependency jest to v22.4.0
  package.json
  yarn.lock
Labels: dependencies

#223 Update dependency eslint-plugin-import to v2.9.0
  package.json
  yarn.lock
Labels: dependencies

#226 Update dependency nodemon to v1.15.1
  package.json
  yarn.lock
Labels: dependencies

#225 Update dependency lint-staged to v7
  package.json
  yarn.lock
Labels: dependencies

#227 Renovate graphql packages
  package.json
  yarn.lock
Labels: dependencies

#228 Migrate to dataloaders
  package.json
  src/app.js
  src/lib/loaders.js
  src/models/Question.js
  src/models/QuestionInstance.js
  src/models/Session.js
  src/models/Tag.js
  src/resolvers/questionInstances.js
  src/resolvers/questions.js
  src/resolvers/sessions.js
  src/resolvers/tags.js
  src/services/__snapshots__/questions.test.js.snap
  src/services/questions.js
  yarn.lock
Labels: enhancement

#229 Pin dependency dataloader to v1.4.0
  package.json
  yarn.lock
Labels: dependencies

#233 Update Dockerfile node image 8-alpine digest (eae6c7)
  Dockerfile
Labels: dependencies

#232 Update dependency jest to v22.4.2
  package.json
  yarn.lock
Labels: dependencies

#230 Renovate database packages
  package.json
  yarn.lock
Labels: dependencies

#231 Update dependency nodemailer to v4.6.0
  package.json
  yarn.lock
Labels: dependencies
